version: '3.8'

services:
  # Python Flask Backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: healthcare-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./api/models:/app/models
      - ./api/trained_models:/app/trained_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-frontend
    ports:
      - "80:80"
      - "3000:80"  # Alternative port for development
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  # Optional: Ganache for blockchain development
  ganache:
    image: trufflesuite/ganache:latest
    container_name: healthcare-ganache
    ports:
      - "7545:8545"
    command: >
      ganache
      --wallet.deterministic
      --wallet.accounts=10
      --wallet.defaultBalance=100
      --database.dbPath=/ganache_data
    volumes:
      - ganache_data:/ganache_data
    restart: unless-stopped

volumes:
  ganache_data:

networks:
  default:
    name: healthcare-network