version: '3.8'

services:
  # Python Flask Backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: healthcare-backend
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - PORT=${PORT:-5000}
    volumes:
      - ./api/models:/app/models
      - ./api/trained_models:/app/trained_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-frontend
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:5000}
      - PORT=${PORT:-80}

volumes:
  app_data:

networks:
  default:
    name: healthcare-network