# Railway Configuration for Healthcare DApp

# Backend Service Configuration
[backend]
build.dockerfile = "api/Dockerfile"
build.context = "api"

# Frontend Service Configuration  
[frontend]
build.dockerfile = "Dockerfile"
build.context = "."

# Environment Variables
[env]
FLASK_ENV = "production"
NODE_ENV = "production"
PORT = "${PORT}"